version: "3.8"
services:
  gitlab-server:
    image: "gitlab/gitlab-ce:latest"
    container_name: gitlab-server
    ports:
      - "9689:80"
    environment:
      GITLAB_ROOT_EMAIL: "hsimchi74@gmail.com"
      GITLAB_ROOT_PASSWORD: "Hossein!7175"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/data:/var/opt/gitlab
